name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every night at midnight
  workflow_dispatch:      # Optional: lets you manually trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: omkarhole
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
